export const FIND_DEVICE_REQUEST = 'FIND_DEVICE_REQUEST';
export const FIND_DEVICE_SUCCESS = 'FIND_DEVICE_SUCCESS';
export const FIND_DEVICE_FAIL = 'FIND_DEVICE_FAIL';

export const DEVICE_DETAILS_REQUEST = 'DEVICE_DETAILS_REQUEST';
export const DEVICE_DETAILS_SUCCESS = 'DEVICE_DETAILS_SUCCESS';
export const DEVICE_DETAILS_FAIL = 'DEVICE_DETAILS_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

