export const FILTER_PRICE_REQUEST = 'FILTER_PRICE_REQUEST';
export const FILTER_PRICE_SUCCESS = 'FILTER_PRICE_SUCCESS';
export const FILTER_PRICE_FAIL = 'FILTER_PRICE_FAIL';

export const CLEAR_ERRORS = 'CLEAR_ERRORS';

